# Generated by Django 4.2.7 on 2023-11-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bounus',
            new_name='bonus',
        ),
    ]
